version: "3.9"   
services:
  db:
    image: postgres
    volumes:
      - ./data/coinmena:/var/lib/postgresql/data
    ports:
      - "5432:5432"     
    environment:
      - POSTGRES_DB=coinmena
      - POSTGRES_HOST=localhost
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres 
      - POSTGRES_NAME=coinmena 
  web:
    build: .
    command:  >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_PORT=5432  
    env_file:
      ./crypto_price/.env   
    depends_on:
      - db