# Generated by Django 3.2.6 on 2021-08-31 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BtcRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('currency', models.CharField(max_length=256)),
                ('exchange_rate', models.DecimalField(decimal_places=4, max_digits=7)),
                ('last_refresh', models.DateTimeField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
