# Generated by Django 3.2.6 on 2021-08-31 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btc_rate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='btcrate',
            name='exchange_rate',
            field=models.CharField(max_length=256),
        ),
    ]
